name: Firebase Tools

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install firebase-tools
        run: |
          apt-get update && apt-get install default-jre-headless -y
          npm install -g firebase-tools@13.34.0
      - name: Run emulator
        run: |
          firebase emulators:start
